# Generated by Django 3.2.10 on 2024-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
