# Generated by Django 3.2.10 on 2024-01-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0006_alter_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
